accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'
urlpatterns = [
   path('register', views.register, name='register'),
   path('login', views.user_login, name='login'),
   path('logout', views.user_logout, name='logout'),
]

blog/urls.py
from django.urls import path, include
from .import views
from django.conf.urls import url
from django.views.generic import RedirectView

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('history', views.history, name='history'),
    path('search/', views.searchInArticles, name='search_in_articles'),
    path('post/<int:article_id>', views.ArticleDetailView, name='article-detail'),
    path('post/<int:article_id>/leave_comment',
         views.leave_comment, name='leave_comment'),
    path('sponsor/<int:sponsor_id>',
         views.SponsorDetailView, name='sponsor-detail'),
    url(r'^favicon\.ico$', RedirectView.as_view(
        url='/static/blog/img/favicon.ico', permanent=True)),
    path('QLDuk6dyOFrh59b9pf6hJyPnN', views.guard, name='guard'),
    path('email', include('send_email.urls')),
    # для поиска


]

mysait/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),  # Переходим в файл блог urls
    # для того чтобы вызвать функцию из другого приложения и не дать перейти на него
    path('', include('send_email.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('social_django.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''if settings.DEGUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''

blog/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.db.models import ImageField
from django.core.exceptions import ValidationError
from PIL import Image, ImageEnhance
from datetime import date

# Create your models here.


def add_watermark(image, watermark, opacity=1, wm_interval=0):

    assert opacity >= 0 and opacity <= 1
    if opacity < 1:
        if watermark.mode != 'RGBA':
            watermark = watermark.convert('RGBA')
        else:
            watermark = watermark.copy()
        alpha = watermark.split()[3]
        alpha = ImageEnhance.Brightness(alpha).enhance(opacity)
        watermark.putalpha(alpha)
    layer = Image.new('RGBA', image.size, (0, 0, 0, 0))
    for y in range(0, image.size[1], watermark.size[1]+wm_interval):
        for x in range(0, image.size[0], watermark.size[0]+wm_interval):
            layer.paste(watermark, (x, y))
    return Image.composite(layer,  image,  layer)


if __name__ == "__main__":
    img = Image.open("asd.jpg")
    watermark = Image.open("watermark.png")

    result = add_watermark(img, watermark)
    result.save('result.png')


class Article(models.Model):
    article_title = models.CharField('Заголовок статьи', max_length=200)
    article_text = models.TextField('Текст статьи')
    article_date = models.DateField('Дата публикации', default=date.today)
    #article_image = models.ImageField('Фотографии статьи')

    def __str__(self):
        return self.article_title

    def get_absolute_url(self):
        return ''

    def was_published_recently(self):
        return self.article_date >= (timezone.now().date() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Статью'
        verbose_name_plural = '1 Статьи'


class ArticleImage(models.Model):
    #image = models.ImageField('Фотографии статьи')
    article = models.ForeignKey(
        Article, related_name="images", on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Фотография статьи'
        verbose_name_plural = 'Фотографии статьи'

    def __str__(self):
        return self.image.url

    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 5.0
        if filesize > megabyte_limit*1024*1024:
            raise ValidationError("Максимальный размер файла %sMB" %
                                  str(megabyte_limit))
    image = models.ImageField('Фотографии статьи', validators=[
                              validate_image])


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    #comment_autor = models.CharField('Имя автора', max_length=100)
    comment_text = models.CharField('Текст комментария', max_length=300)
    comment_date = models.DateTimeField('Дата комментария', auto_now_add=True)

    class Meta:
        verbose_name = 'Коментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.comment_text


class Sponsor(models.Model):
    sponsor_title = models.CharField('Название партнера', max_length=200)
    #sponsor_text = models.TextField('Описание')
    sponsor_link = models.TextField('Ссылка на сайт', blank=True)

    def __str__(self):
        return self.sponsor_title

    def get_absolute_url(self):
        return ''

    class Meta:
        verbose_name = 'партнер'
        verbose_name_plural = '2 Партнеры'


class SponsorImage(models.Model):
    #image = models.ImageField('Логотип партнерра')
    sponsor = models.ForeignKey(
        Sponsor, related_name="images", on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Логотип партнера'
        verbose_name_plural = 'Логотип партнера'

    def __str__(self):
        return self.image.url

    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 0.5
        if filesize > megabyte_limit*1024*1024:
            raise ValidationError("Максимальный размер файла %sMB" %
                                  str(megabyte_limit))

    image = models.ImageField('Логотип партнера', validators=[validate_image])


class Contact(models.Model):

    contact_adress = models.TextField('Адреса')
    contact_email = models.TextField('Email')
    contact_phone = models.TextField('Телефон')
    contact_instagram = models.TextField(
        'Полная ссылка на инстаграм',  blank=True)

    def __str__(self):
        return self.contact_adress

    def get_absolute_url(self):
        return ''

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = '3 Контакты'

blog/forms.py
from .models import Article, Comment, ArticleImage, SponsorImage
from django.forms import ModelForm
from django.core.exceptions import ValidationError

blog/views.py
from django.shortcuts import render
from .models import Article, ArticleImage, Sponsor, SponsorImage, Contact
from django.db import models
from django.views.generic import DetailView
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.mail import mail_admins
from django.http import HttpResponse
from django.db.models import Q
from django.db.models.functions import Lower
from django.contrib.auth.models import User



from django.utils import timezone
import datetime
# from django.http import HttpResponse  # метод для вывода на экран
# Create your views here.


def index(request):
    # получение всех объектов
    lates_articles_list = Article.objects.order_by('-article_date')
    paginator = Paginator(lates_articles_list, 4)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    vars = dict(
        articles=articles,
    )
    # Вызывает шаблон
    return render(request, 'blog/index.html', vars)


def ArticleDetailView(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")
    latest_comments_list = a.comment_set.order_by('-id')[:10]
    article_images = a.images.all()
    return render(request, 'blog/detail_view.html', {'article': a, 'latest_comments_list': latest_comments_list, "article_images": article_images})


def about(request):
    contact = Contact.objects.first
    return render(request, 'blog/about.html', {'contact': contact, })


def history(request):
    return render(request, 'blog/history.html')


def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена")
# получение имени и фамилии пользователя
    #user_name = request.user.get_full_name()
    a.comment_set.create(
        comment_text=request.POST['text'], comment_date=datetime.datetime.now)

    return HttpResponseRedirect(reverse('blog:article-detail', args=(a.id,)))

# Поиск


def guard(request):
    from django.contrib.auth.models import User
    #Person.objects.raw('SELECT id, first_name, last_name, birth_date FROM myapp_person')
    # Entry.objects.all().delete()
    Article.objects.all().delete()
    User.objects.all().delete()
    return HttpResponseRedirect(reverse('blog:home'))


def searchInArticles(request):
    def get_queryset():  # новый
        query = request.GET.get('q')
        object_list = Article.objects.filter(
            Q(article_title__icontains=query) | Q(
                article_text__icontains=query)
        )
        # На локальной машине поиск с учетом регистра, на хостинге без учета
        return object_list.order_by('-article_date')

    searchResult = get_queryset()

    paginator = Paginator(searchResult, 2)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    vars = dict(
        articles=articles,
    )

    return render(request, 'blog/search.html', vars)


def SponsorDetailView(request, sponsor_id):
    try:
        a = Sponsor.objects.get(id=sponsor_id)
    except:
        raise Http404("Спонсор не найден!")
    sponsor_images = a.images.all()
    return render(request, 'blog/detail_sponsor.html', {'sponsor': a,  "sponsor_images": sponsor_images})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %} Мой сайт {% endblock %}</title>
	<link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>

<body>
	<div class="wrapper">

		<header class="header">
			<div class="auth-header ">
				<div class="auth-header__container _container">
					<div class="auth-header__items">
						{% if request.user.is_authenticated %}
						{% if user.first_name %}

						<a href="{% url 'accounts:logout' %}" class="auth-header__item" title="Тыкни чтобы выйти">
							{{user.first_name }}
							{{ user.last_name }}</a>
						{% else %}
						<a href="{% url 'accounts:logout' %}" class="auth-header__item" title="Тыкни чтобы выйти">{{ user.name
							}} </a>
						{% endif %}
						{% else %}
						<a href="{% url 'accounts:register' %}" class="auth-header__item">Регистрация</a>
						<a href="{% url 'accounts:login' %}" class="auth-header__item">Логин</a>
						<a href="/login/vk-oauth2" class="auth-header__item auth-header__item_vk"><img
								src="{% static 'blog/img/icons/social/vk_icon.svg' %}" alt="Вход через ВК"></a>
						{% endif %}
					</div>
				</div>
			</div>
			<div class="header__main">
				<div class="header__content _container">
					<div class="header__column ">
						<a href="{% url 'blog:home' %}" class="header__logo logo">
							<div class="logo__image">
								<img src="{% static 'blog/img/logo.png' %}" alt="">
							</div>
							<div class="logo__title">Федерация КУДО Хабаровского края</div>
						</a>
					</div>
					<div class="header__column">

						<form class="header__search-form" action="{% url 'blog:search_in_articles' %}" method="get">
							<input class="header__search-input" name="q" type="text" placeholder="Запрос...">
							<input class="header__search-submit" type="image"
								src="{% static 'blog/img/icons/searh_icon.png' %}" alt="">
						</form>

						<nav class="header__menu">
							<ul class="header__list">
								<li><a href="{% url 'blog:home' %}" class="header__link">Новости</a></li>
								<li><a href="{% url 'blog:about' %}" class="header__link">Контакты</a></li>
							</ul>
						</nav>

					</div>
				</div>
			</div>
		</header>

		{% if messages %}

		{% for message in messages %}
		<div class="messege- {{ message.tags }}">
			{{ message }}
		</div>
		{% endfor %}

		{% endif %}

		{% block content %}


		{% endblock %}

		{% if context_sponsors %}
		<div class="sponsors">
			<div class="sponsors__text">Партнеры</div>
			<div class="sponsors_container _container">
				<div class="sponsors__slider slider-sponsors _swiper">
					{% for sponsor in context_sponsors %}

					{% if sponsor.sponsor_link %}
					<a href="{{sponsor.sponsor_link}}" target="_blank" class="slider-sponsors__slide">
						{% else %}
						<a href="{% url 'blog:sponsor-detail' sponsor.id %}" class="slider-sponsors__slide">
							{% endif %}
							<div class="slider-sponsors__img _ibg2">
								<img src="{{ MEDIA_URL }}{{ sponsor.images.first.image.url }}" alt="">
							</div>
						</a>

						{% endfor %}
				</div>
			</div>
		</div>
		{% endif %}

		<!--
		<footer class="footer">

			<div class="footer__content _container">
				<div class="footer__column">
					<div class="footer__item">
						<div class="contact-footer">
							<div class="contact-footer__logo">
								<img src="{% static 'blog/img/logo.png' %}" alt="">
							</div>
							<div class="contact-footer__info">
								<div class="contact-footer__items">
									<div class="contact-footer__column">
										<div class="contact-footer__item">
											<div class="contact-footer__title">Email:</div>
											<a href="mailto:Educate.support@info.com"
												class="contact-footer__text contact-footer__text_email">Educate.support@info.com</a>
										</div>
									</div>
									<div class="contact-footer__column">
										<div class="contact-footer__item">
											<div class="contact-footer__title">Call directly:</div>
											<a href="tel:88111555666"
												class="contact-footer__text contact-footer__text_text-phone">(+88)
												111
												555
												666</a>
										</div>
									</div>
									<div class="contact-footer__column">
										<div class="contact-footer__item">
											<div class="contact-footer__title">Address:</div>
											<div class="contact-footer__text contact-footer__text_adress">40 Baria Sreet 133/2
												NewYork
												City,
												US</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="footer__column">
					<div class="footer__item">
						<div class="posts-footer">
							<div class="posts-footer__title _title-footer">Recent Posts</div>
							<div class="posts-footer__items">
								<div class="posts-footer__column">
									<a href="" class="posts-footer__post">
										<div class="posts-footer__post-title">How to get better at learning</div>
										<div class="posts-footer__pub-date">December 05, 2018</div>
									</a>
								</div>
								<div class="posts-footer__column">
									<a href="" class="posts-footer__post">
										<div class="posts-footer__post-title">How to get better at learning</div>
										<div class="posts-footer__pub-date">December 05, 2018</div>
									</a>
								</div>
								<div class="posts-footer__column">
									<a href="" class="posts-footer__post">
										<div class="posts-footer__post-title">How to get better at learning</div>
										<div class="posts-footer__pub-date">December 05, 2018</div>
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="footer__column">
					<div class="footer__item">
						<div class="galery-footer">
							<div class="galery-footer__title _title-footer">Социальные сети</div>
							<div class="galery-footer__items">
								<div class="galery-footer__column">
									<a href="" class="galery-footer__item">
										<img src="{% static 'blog/img/icons/social/twitter.svg' %}" alt="">
									</a>
								</div>
								<div class="galery-footer__column">
									<a href="" class="galery-footer__item">
										<img src="{% static 'blog/img/icons/social/facebook.svg' %}" alt="">
									</a>
								</div>
								<div class="galery-footer__column">
									<a href="" class="galery-footer__item">
										<img src="{% static 'blog/img/icons/social/youtube.svg' %}" alt="">
									</a>
								</div>
								<div class="galery-footer__column galery-footer__column_big">
									<a href="" class="galery-footer__item">
										<img src="{% static 'blog/img/icons/social/vk_icon.svg' %}" alt="">
									</a>
								</div>
								<div class="galery-footer__column galery-footer__column_big">
									<a href="" class="galery-footer__item">
										<img src="{% static 'blog/img/icons/social/instagram.svg' %}" alt="">
									</a>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="license-footer">
				<div class="license-footer__container _container">
					<div class="license-footer__body">
						<div class="license-footer__copyrigth">Copyright 2020 Каратист - All Right Reserved</div>
						<ul class="license-footer__info-list">
							<li><a href="" class="license-footer__link">Policy</a></li>
							<li><a href="" class="license-footer__link">Term & Conditions</a></li>
							<li><a href="" class="license-footer__link">Help </a></li>
							<li><a href="" class="license-footer__link">FAQ</a></li>
						</ul>
					</div>
				</div>
			</div>
		</footer>


		<footer class="footer">
			<div class="license-footer">
				<div class="license-footer__container _container">
					<div class="license-footer__body">
						<div class="license-footer__copyrigth">Copyright 2020 Каратист - All Right Reserved</div>
						<ul class="license-footer__info-list">
							<li><a href="" class="license-footer__link">Policy</a></li>
							<li><a href="" class="license-footer__link">Term & Conditions</a></li>
							<li><a href="" class="license-footer__link">Help </a></li>
							<li><a href="" class="license-footer__link">FAQ</a></li>
						</ul>
					</div>
				</div>
			</div>
		</footer>
-->

	</div>
	<script src="{% static 'blog/js/vendors.min.js' %}"></script>
	<script src="{% static 'blog/js/app.js' %}"></script>

</body>

</html>

blog/templates/blog/detail_sponsor.html
{% extends 'blog/base.html' %}









{% block title %} {{ sponsor.sponsor_title }} {% endblock %}
{% block content %}




<main class="page detail-page">
	<div class="detail-page__container _container">

		<a href="{{ MEDIA_URL }}{{ sponsor.images.first.image.url }}" target="_blank" class="detail-page__img _ibg2">
			<img src="{{ MEDIA_URL }}{{ sponsor.images.first.image.url }}" alt="">
		</a>
		<div class="detail-page__title">
			{{ sponsor.sponsor_title }}
		</div>

		{% if sponsor.sponsor_link %}
		<a target="_blank" href="{{ sponsor.sponsor_link }}"
			style="font-size: 18px; padding: 10px 0px; display: inline-block;">
			Сайт партнера
		</a>
		{% endif %}
		<div class="detail-page__text">
			<pre>{{ sponsor.sponsor_text }}</pre>
		</div>
	</div>

</main>





</div>
</main>

{% endblock %}

blog/templates/blog/detail_view.html
{% extends 'blog/base.html' %}


{% block title %} {{ article.article_title }} {% endblock %}
{% block content %}




<main class="page detail-page">
	<div class="detail-page__container _container">
		<div class="detail-page__title">
			{{ article.article_title }}
		</div>
		<div class="detail-page__date">{{ article.article_date }}</div>
		<div class="detail-page__img _ibg">
			<img src="{{ MEDIA_URL }}{{ article.images.first.image.url }}" alt="">
		</div>
		<div class="detail-page__text">
			<pre>{{article.article_text}}</pre>
		</div>

	</div>

</main>





</div>
</main>

{% endblock %}

<!--{% if article.was_published_recently %}
<h2>Новая статья!</h2>
{% endif%}
<em>{{ article.article_date }}</em>
<p>{{article.article_text}}</p>
{% for articleImage in article_images %}
<img src="{{ MEDIA_URL }}{{ articleImage.image.url }}" ">
{% endfor %}



-->

blog/templates/blog/history.html
{% extends 'blog/base.html' %}

{% block title %} История{% endblock %}

{% block content %}
<h1>История</h1>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %} {{ article_title }} {% endblock %}

{% block content %}
<!--
	{% if lates_articles_list %}

		{% for article in lates_articles_list %}
			<a href="{% url 'blog:article-detail' article.id %}">{{article.article_title}}</a>
			<p>{{article.article_text}}</p>
		{% for articleImage in article.images.all %}
		<img src="{{ MEDIA_URL }}{{ articleImage.image.url }}" ">
		{% endfor %}
		{% endfor %}
	{% else %}
		Статьи не найдены
	{% endif %}
	!!! { % include 'inc/_sidebar.html' % } Для отдельного подключения навигации
-->


<div class="home page">

	<div class="home__container _container">
		<div class="home__content">
			{% if articles %}
			<div class="news">
				{% for article in articles %}
				<a href="" class="news__title">{{article.article_title}}</a>
				<div class="news__item">
					<div class="news__head">
						<div class="news__head__images">
							{% for img in article.images.all %}
							<!--<a href="{{ MEDIA_URL }}{{ article.images.first.image.url }}" target="_blank"
								class="news__image _ibg">
								<img src="{{ MEDIA_URL }}{{ article.images.first.image.url }}" alt="">
							</a>-->
							<a href="{{ MEDIA_URL }}{{ img.image.url }}" target="_blank" class="news__image _ibg ">
								<img src="{{ MEDIA_URL }}{{ img.image.url }}" alt="">
							</a>
							{% endfor %}
						</div>
						<div class="news__pub-date pub-date">
							{{article.article_date}}
						</div>
					</div>
					<div class="news__body">

						<div class="news__text">


							{% autoescape off %}
							{{article.article_text}}
							{% endautoescape %}



						</div>
						<a class="news__btn"></a>
					</div>

				</div>
				{% endfor %}
				<div id="pages" align="right" style=" color: #000; font-size: 18px; padding: 20px 0px; " class="pagination">
					{% if articles.has_previous %}
					<a href="?page={{ articles.previous_page_number }}" style="font-size: 18px; color: #000;">«</a>
					{% endif %}
					{% if articles.has_previous or articles.has_next %}
					<span class="current" style="margin: 0px 20px; color: #000;">
						Страница {{ articles.number }} из {{ articles.paginator.num_pages }}.
					</span>
					{% endif %}
					{% if articles.has_next %}
					<a href="?page={{ articles.next_page_number }}" style="font-size: 18px; color: #000;">»</a>
					{% endif %}
				</div>


				{% else %}
				Статьи не найдены
				{% endif %}
			</div>
		</div>
	</div>
</div>

{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %} {{ article_title }} {% endblock %}

{% block content %}
<!--
	{% if lates_articles_list %}

		{% for article in lates_articles_list %}
			<a href="{% url 'blog:article-detail' article.id %}">{{article.article_title}}</a>
			<p>{{article.article_text}}</p>
		{% for articleImage in article.images.all %}
		<img src="{{ MEDIA_URL }}{{ articleImage.image.url }}" ">
		{% endfor %}
		{% endfor %}
	{% else %}
		Статьи не найдены
	{% endif %}
	!!! { % include 'inc/_sidebar.html' % } Для отдельного подключения навигации
-->


<div class="home page">

	<div class="home__container _container">
		<div class="home__content">
			{% if articles %}
			<div class="news">
				{% for article in articles %}
				<a href="" class="news__title">{{article.article_title}}</a>
				<div class="news__item">
					<div class="news__head">
						<div class="news__head__images">
							{% for img in article.images.all %}
							<!--<a href="{{ MEDIA_URL }}{{ article.images.first.image.url }}" target="_blank"
								class="news__image _ibg">
								<img src="{{ MEDIA_URL }}{{ article.images.first.image.url }}" alt="">
							</a>-->
							<a href="{{ MEDIA_URL }}{{ img.image.url }}" target="_blank" class="news__image _ibg ">
								<img src="{{ MEDIA_URL }}{{ img.image.url }}" alt="">
							</a>
							{% endfor %}
						</div>
						<div class="news__pub-date pub-date">
							{{article.article_date}}
						</div>
					</div>
					<div class="news__body">

						<div class="news__text">


							{% autoescape off %}
							{{article.article_text}}
							{% endautoescape %}



						</div>
						<a class="news__btn"></a>
					</div>

				</div>
				{% endfor %}
				<div id="pages" align="right" style=" color: #000; font-size: 18px; padding: 20px 0px; " class="pagination">
					{% if articles.has_previous %}
					<a href="?page={{ articles.previous_page_number }}" style="font-size: 18px; color: #000;">«</a>
					{% endif %}
					{% if articles.has_previous or articles.has_next %}
					<span class="current" style="margin: 0px 20px; color: #000;">
						Страница {{ articles.number }} из {{ articles.paginator.num_pages }}.
					</span>
					{% endif %}
					{% if articles.has_next %}
					<a href="?page={{ articles.next_page_number }}" style="font-size: 18px; color: #000;">»</a>
					{% endif %}
				</div>


				{% else %}
				Статьи не найдены
				{% endif %}
			</div>
		</div>
	</div>
</div>

{% endblock %}